apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-test
  labels:
    app: api-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-test
  
  template:
    metadata:
      labels:
        app: api-test
    spec:
        containers:
        - name: api-test-image
          image: registry.digitalocean.com/dev-repositories/demo:lastest
          ports:
          - containerPort: 3000
        imagePullSecrets:
        - name: dev-repositories