---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: api-service-volume-v2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: ""
    path: "/storage/tntt"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-service-volume-claim-v2
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi