apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  
  template:
    metadata:
      labels:
        app: auth-service
    spec:
        containers:
        - name: auth-service-image
          image: registry.digitalocean.com/dev-repositories/auth-service:latest
          ports:
          - containerPort: 3000
          imagePullPolicy: Always
        imagePullSecrets:
        - name: dev-repositories