apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    app: auth-service
  type: ClusterIP # label selectors Pod
  ports:
    - port: 3000 # port of the serivce
      targetPort: 3000