apiVersion: v1
kind: PersistentVolume # Create PV 
metadata:
  name: jenkins-volume # Sets PV name
  labels:
    app: jenkins
    type: local # Sets PV's type
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi # Sets PV's size
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data"

---
apiVersion: v1
kind: PersistentVolumeClaim # Create PVC
metadata:
  name: jenkins-volume-claim # Sets PVC's name
  labels:
    app: jenkins # Defines app to create PVC for
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi