apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-nginx
spec:
  acme:
    email: hxt12021999@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-nginx-private-key
    solvers:
      # Use the HTTP-01 challenge provider
      - http01:
          ingress:
            class: nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    cert-manager.io/issuer: letsencrypt-nginx

spec:
  ingressClassName: nginx

  rules:
    - host: thai-bug.me
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: api-service 
              port:
                number: 3000

  tls:
  - hosts:
    - thai-bug.me
    secretName: letsencrypt-nginx
