apiVersion: apps/v1
kind: Deployment # Create a deployment
metadata:
  name: rbmq # Set the name of the deployment
spec:
  replicas: 3 # Set 3 deployment replicas
  selector:
    matchLabels:
      app: rbmq
  template:
    metadata:
      labels:
        app: rbmq
    spec:
      containers:
        - name: rbmq
          image: rabbitmq:3-management-alpine
          imagePullPolicy: Always
          ports:
            - name: ui 
              containerPort: 15672
            - name: service
              containerPort: 5672
          envFrom:
            - configMapRef:
                name: rbmq-secret
          volumeMounts:
            - mountPath: /var/rabbitmqapp_home
              name: rabbitmqapp-home
      volumes:
        - name: rabbitmqapp-home
          emptyDir: {}

