apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: production
  labels:
    app: storageos
provisioner: csi.storageos.com # CSI Driver
parameters:
  storageos.com/replicas: "2"
  csi.storage.k8s.io/controller-expand-secret-name: csi-controller-expand-secret 
  csi.storage.k8s.io/controller-expand-secret-namespace: kube-system
  csi.storage.k8s.io/controller-publish-secret-name: csi-controller-publish-secret
  csi.storage.k8s.io/controller-publish-secret-namespace: kube-system
  csi.storage.k8s.io/fstype: ext4
  csi.storage.k8s.io/node-publish-secret-name: csi-node-publish-secret
  csi.storage.k8s.io/node-publish-secret-namespace: kube-system
  csi.storage.k8s.io/provisioner-secret-name: csi-provisioner-secret
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system