---
apiVersion: v1
kind: Service
metadata:
  name: rbmq
spec:
  type: NodePort
  ports:
    - name: ui
      port: 15672
      targetPort: 15672
      nodePort: 32596
    - name: service
      port: 5672
      targetPort: 5672
      nodePort: 31111
  selector:
    app: rbmq