apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-master-data
  labels:
    type: local 
    app: redis-master
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi # Sets PV's size
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/data-master0"

---
apiVersion: v1
kind: PersistentVolumeClaim # Create PVC
metadata:
  name: redis-master-claim # Sets PVC's name
  labels:
    app: redis-master # Defines app to create PVC for
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi