---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-replicas-data
  labels:
    type: local 
    app: redis-replicas
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/data-replicas0"

---
apiVersion: v1
kind: PersistentVolumeClaim # Create PVC
metadata:
  name: redis-replicas-claim # Sets PVC's name
  labels:
    app: redis-replicas # Defines app to create PVC for
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi


